require: []

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - "pkg/**/*"

# ── Style ──

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true

Style/GuardClause:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/RescueStandardError:
  EnforcedStyle: implicit

Style/StringConcatenation:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

# ── Metrics ──

Metrics/MethodLength:
  Max: 30
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Metrics/AbcSize:
  Max: 35
  Exclude:
    - "spec/**/*"

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 12

Metrics/ClassLength:
  Max: 250

Metrics/ParameterLists:
  Max: 8

# ── Layout ──

Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# ── Naming ──

Naming/AccessorMethodName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

# ── Lint ──

Lint/UnusedBlockArgument:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/SharedMutableDefault:
  Enabled: false

# ── Gemspec ──

Gemspec/RequireMFA:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false
